export { default as LoanPage } from './loan'
export { default as LoanJoinDetailPage } from './loanDetail'
export { default as LoanJoinInfoPage } from './loanJoinInfo'
export { default as LoanJudgePage } from './loanJudge'
export { default as LoanJoinOkPage } from './loanJoinOk'